spec:
  template:
    spec:
      containers:
      - env:
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: "clientId"
              name: "springboot-kc-client"
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: "clientSecret"
              name: "springboot-kc-client"
        - name: SPRING_CONFIG_LOCATION
          value: "/config/application.yml"
        volumeMounts:
        - name: springboot-app-config
          mountPath: /config/
      volumes:
        - name: springboot-app-config
          configMap:
            name: springboot-keycloak
